### ISSUE TITLE
seems gnome-extension version is down

### ISSUE THREAD

**Issue by zba** [CZ-NIC/run-or-raise#12]
I tried to update from gnome-extension page, seems not all needed files updated, etc, I fixed from git, may be need to update ?

**Comment by e3rd** [comment]
Hi, zba, I've tried to update gnome-extensions few days ago but that version still waits for a review

https://extensions.gnome.org/extension/1336/run-or-raise/

![image](https://user-images.githubusercontent.com/6942231/40580810-69f9e89e-6147-11e8-8363-4f96a5a9905e.png)

I hope next week somebody'll review it.
