### ISSUE TITLE
Bug when cycling through windows (when hotkey hit twice)

### ISSUE THREAD

**Issue by dmocek** [CZ-NIC/run-or-raise#14]
First off, thank you for this awesome tool.  I cannot tell you how productive this makes me and how much more enjoyable my development process is as a result.

This is how to reproduce the bug:
- Start any app using a shortcut (e.g. Google Chrome using Super-G)
- Start any other app using a shortcut. (e.g. GNOME Terminal using Super-T)
- Use Super-G to go to Chrome.  Now use Super-G again and Terminal will show.  This repeats...Chrome-Terminal-Chrome etc.  Super-G should never take you to Terminal.

This is only a problem when using a single window.  The behavior I expect is that if I have a single window, then hitting the hotkey I've assigned will keep me on the app's window.  It's strange hitting the hot key for an app and having it take me to another app, then back.

**Comment by e3rd** [comment]
Thanks, glad to hear that :)

You're describing a very strange behaviour. Sure, hitting a hot key twice shouldn't take you to another application. If I hit it twice, I stay in the same application, hundred times a day. Could you paste here your config file please so that I can inspect it?

**Comment by dmocek** [comment]
Here it is.  This happens on all apps.

<Super>b,vivaldi,Vivaldi,
<Super>e,emacs,Emacs,

# This line cycles any firefox window (matched by "firefox" in the window title) OR if not found, launches new firefox instance.
<Super>f,firefox,Firefox,

<Super>g,google-chrome,Google-chrome,

<Super>h,cherrytree /home/dmocek/MyFiles/SlooceNotes.ctb,Cherrytree,
<Super>i,/snap/intellij-idea-ultimate/79/bin/idea.sh,jetbrains-idea,
<Super>m,thunderbird,Thunderbird,

# This line cycles any open gnome-terminal (matched by wm_class = Gnome-terminal on Ubuntu 17.10) OR if not found, launches new one.
# If you're using Arch, you may want to match by wm_class = gnome-terminal-server , just check yourself by Alt+F2/lg/Windows
<Super>r,gnome-terminal,Gnome-terminal,

# Terminator terminal
<Super>t,terminator,Terminator,

# Zeal documentation tool.
<Super>d,zeal,Zeal,
<Super>u,clementine,,
<Super>q,/home/dmocek/Programs/squirrel-sql/squirrel-sql-3.7.1/squirrel-sql.sh,net-sourceforge-squirrel_sql-client-Main,
<Super>s,skype,Skype,
<Super>y,pithos,Pithos,
<Super>z,zoom,Zoom,

**Comment by dmocek** [comment]
I have a second machine I have this installed on and it doesn't display this behavior.  There must be something else going on.

**Comment by e3rd** [comment]
Is there a difference between OSes?

**Comment by dmocek** [comment]
I do still see the issue.  Both machines, the one I see the problem on and the one I don't see the problem on are Ubuntu 18.04 LTS.  I see the issue regardless of the hotkey and regardless of the application it launches.

**Comment by e3rd** [comment]
When both Chrome and Terminal are open, first `Super-G` takes you to Chrome and another one to Terminal.

* Do you think Chrome gets minimized on the second strike or anything else happens?
* What is the behaviour when there are three apps?
* If there are other application than terminal, will it take you to this one, or the strange behaviour appear only when Terminal is present?

**Comment by dmocek** [comment]
None of the apps get minimized.
Having more than two apps doesn't change the behavior.
This happens on every app, not just Terminal and Chrome.  I just used those as examples.

Here's the behavior:
- Launch any app using hot keys.  Doesn't matter which one.  In this case, I use Chrome with Super-G.  Make sure there's only one application window running.
- Launch any other app using hot keys.  Doesn't matter  one.  In this case, I use Terminal with Super-T.  Make sure there's only one application window running.
- Hit Super-G to go to the first app.  With focus on the first app, hit the same hot key (in this case Super-G).  The second app will get focus.  Continuing to hit the hot key will switch the focus between the first and second apps.
- Start any third app using hot keys.  Doesn't matter which one.  In this case, I use Emacs with Super-E.  Make sure there's only one application window running.
   - With the focus on Emacs, hit Super-T.  Terminal will get the focus.  Hit Super-T again, Emacs will get the focus.
   - With the focus on Emacs, hit Super-G.  Chrome will get the focus.  Hit Super-G again, Emacs will get the focus.

What is happening is that when an app which has only one window has focus and you hit the hot keys to go to another app which also has only one window, the hot key will switch the focus between the two apps.  When you use the hot keys to go to an app with more than one window, doesn't matter if you're switching from an app with one or more than one window, the focus will go to that app and will remain there.  Hitting the hot keys will switch between that apps multiple windows.

**Comment by e3rd** [comment]
Don't you have "Switch back when focused" option checked on the erroneous machine?

![image](https://user-images.githubusercontent.com/6942231/47153276-0a745d80-d2d7-11e8-89eb-296b80086c58.png)

**Comment by e3rd** [comment]
No reaction for two weeks, closing.
