### ISSUE TITLE
Feature request - Run, Raise or lower

### ISSUE THREAD

**Issue by xircon** [CZ-NIC/run-or-raise#17]
As per title:

+ If not running, run

+ if running, bring to front.

+ If window is focused, lower.

I have a script that can do this for X, but as it extensively uses wmctrl & xdotool it will not function under Wayland.

**Comment by e3rd** [comment]
I programmed this functionality several years ago for [jumpapp](https://github.com/mkropat/jumpapp/pull/12). But however, what should be done if there is a group of windows? Now when hitting the shortcut when in a Firefox window, another Firefox window gets the focus.

**Comment by xircon** [comment]
I only have one window open for firefox, file manager and editor, so not a problem for me, but point taken.

My use case is:
Left Control - tap - terminal
Left Alt - tap - browser
Right Shift - tap - file manager

I have found a program that in combination with run-or-raise gives me back (nearly) all the functionality I got from xcape:

https://github.com/exrok/evdoublebind

It is very new, has no fancy setup (requires musl & musl headers to compile and you have to edit the source and recompile for every change).  But it works.

**Comment by zba** [comment]
It should already work, if there two windows with same match it switch between them, if only one - lower.

**Comment by e3rd** [comment]
Yes, @zba is right, we've done this feature more than a year ago in #10 , I just forgot. 

All you need to do is to toggle a slider in the options. 

![image](https://user-images.githubusercontent.com/6942231/68617912-8506b100-04c8-11ea-8df6-05cb0ec0b233.png)

In case of further question, tell us!
