### ISSUE TITLE
wmclass regex clash

### ISSUE THREAD

**Issue by rostovtsev** [CZ-NIC/run-or-raise#18]
When having wmclass `Google-chrome` called, it also triggers `Google-chrome-beta`. It shouldn't happen, as it gets impossible to call only Google Chrome, without calling Google Chrome Beta.

**Example:**

```
<Shift>F1,gtk-launch google-chrome.desktop,Google-chrome,
<Shift><Alt>c,gtk-launch google-chrome-beta.desktop,Google-chrome-beta,
```

Clicking `Shift+F1` in my case always calls (circles) Google Chrome Beta as well.

Can this be fixed?

**Comment by e3rd** [comment]
Thanks for the bug report, this really seems as the run-or-raise fault. I'll try to fix it in few days.

**Comment by rostovtsev** [comment]
Thanks a bunch! :wink:

**Comment by e3rd** [comment]
I considered everything and finally made no change to the code. Just use regular expressions, that's the perfect solution:

```
<Shift>F1,gtk-launch google-chrome.desktop,/Google-chrome$/,
<Shift><Alt>c,gtk-launch google-chrome-beta.desktop,Google-chrome-beta,
```

**Comment by rostovtsev** [comment]
Brilliant, I didn't know you can use regex there. 

Thanks.
