### ISSUE TITLE
upgrade wipes out shortcuts.conf!

### ISSUE THREAD

**Issue by e3rd** [CZ-NIC/run-or-raise#19]
From the e-mail reports:

What's wrong?
My shortcuts.conf got wiped out....again.  I received a notification that some extensions have updates available, so I went to the update page.  I clicked on the green icon to update and the pop-up window displayed...but then remembered that the last time I updated, my shortcuts.conf got overwritten (see message from qooob).  So I either canceled or just left the pop-up up.  I went to ~/.local/share/gnome-shell/extensions to backup my shortcuts.conf (which I pretty sure I already did...named it shortcuts.conf.mine) only to see that the entire run-or-raise directory was gone...including my backup.

What have you tried?

Automatically detected errors:

GNOME Shell Extensions did not detect any errors with this extension.

Version information:

    Shell version: 3.28.4
    Extension version: 4

**Comment by e3rd** [comment]
Fortunately somebody have send me this issue report so that I know about the problem. I've just checked the extension page and seen people are complaining about this for six months without telling me :(

![image](https://user-images.githubusercontent.com/6942231/69076241-5b530a00-0a33-11ea-9ace-0784e2fb8a77.png)

**Comment by dmocek** [comment]
Thanks e3rd!  Re-creating shortcuts.conf can be tedious.

**Comment by e3rd** [comment]
I've changed the config file location to a one in `$HOME/.config`.
Unfortunately, I could not find a way to make Gnome do not wipe out the `shorcuts.conf` while the upgrade to the newest version. So your file has to be wiped out one last time. I've put a big exclamation marks both to the README and to the description on the Gnome extensions page to backup when upgrading. (And I put this notification out when new Ubuntu LTS is out in the end of April.)

**Comment by dmocek** [comment]
Thanks!  Thanks for your work on this extension e3rd!
