### ISSUE TITLE
wm.get_center is not a function

### ISSUE THREAD

**Issue by jdeut** [CZ-NIC/run-or-raise#20]
On raising a window from behind the following error is logged:

```
Mar 11 09:42:12 johannes gnome-shell[1512272]: JS ERROR: TypeError: wm.get_center is not a function
                                               focusWindow@/home/johannes/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz/extension.js:227:24
                                               jumpapp/<@/home/johannes/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz/extension.js:132:21
                                               _onAccelerator@/home/johannes/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz/extension.js:61:13
                                               wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                               _init/<@/home/johannes/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz/extension.js:25:17
```

It's certainly not a critical bug because everything works a expected.

I just want you to know

**Comment by e3rd** [comment]
Interesting, would you please share the OS version? `wm.get_center` is a GNOME function and maybe was renamed or something.

It seems you have `center-mouse-to-focused-window` option toggled on (and that feature is not working due to the get_center).

**Comment by e3rd** [comment]
ping

**Comment by jdeut** [comment]
Thank your for your answer! And sorry for being inattentive.

Indeed `center-mous-to-focused-window` was enabled. The message isn't triggered anylonger!

Thank your for your effort and best regards
