### ISSUE TITLE
name of keys in configuration

### ISSUE THREAD

**Issue by whysthatso** [CZ-NIC/run-or-raise#25]
gnome-shell 3.36.5 + wayland

i'm trying to use F1-F12 for shortcuts, but can't seem to figure out how they should be referred to in the config file.

i've tried
f1
F1
\<f1>
\<F1>
but to no avail. any pointers?

**Comment by e3rd** [comment]
Will you paste the whole line please? :) I ll try to take a look a it the
next week

**Comment by whysthatso** [comment]
this example works

    <Super>j,tilix,tilix,

this is what i'd prefer

    f1,tilix,tilix

**Comment by e3rd** [comment]
Hello, on my Ubuntu 19.10, the right way is <kbd>F1</kbd>. However, the OS reserves some of the shortcuts (I remember I was not able to re-bind "Ctrl+p" or something similar, reserved for system printing).

Have you tried other F-keys other than <kbd>F1</kbd>? What system are you using? I am using symbol names from `/usr/share/X11/xkb/symbols/`

```
<Super>F4,notify-send "hello super+f4"
F4,notify-send "hello f4"
<Super><Ctrl>F1,notify-send "hello ctrl+super+f1"
F1,notify-send "hello f1"
# does not work, always runs Ubuntu action <Super>F1,notify-send "hello super+f1"
```

**Comment by whysthatso** [comment]
thanks for documenting that here. i can confirm that `F1` etc works. indeed it seems that `F1` has magical powers and can't be rebound. so i went for `F2,tilix,tilix,` and now all is well.

**Comment by e3rd** [comment]
Cool! :)
