### ISSUE TITLE
slashable commas?

### ISSUE THREAD

**Issue by e3rd** [CZ-NIC/run-or-raise#3]
For chromium app window, I'd like to specify window size flag. Nevertheless, that uses commas:  
`--window-size=300,200,,Time tracker`

Would we:
* make somehow comma slashable
* put argument into `"`s
* look how other projects treat this

**Comment by e3rd** [comment]
Python has `csv.reader` with the `"` as a quoting mark.

**Comment by e3rd** [comment]
That one is perfect https://stackoverflow.com/a/11457952/2036148

**Comment by darkermatter** [comment]
As I have a PR open which relies on the current scheme, perhaps it could be done like sed when you want to replace slashes...
Use ```|``` as an alternative separator. If the character appears in the string, use it for the split. If not, just default to the comma. That way, existing configurations won't break.

**Comment by e3rd** [comment]
Seems like a good idea! And I'd like to use an existing way (like the sed one). But what about the case there are both comma and pipe used in the title? You may want to match a page title with a pipe inside. Or you use a regular expression to match the title. How would that work?

**Comment by darkermatter** [comment]
Perhaps have a third separator such as @ and hope nobody needs more than one in the title?

Also, isn't it better to get something working and then solve edge cases later?

**Comment by e3rd** [comment]
Haha, I fear the edge cases would force us to change the syntax and make a
backwards incompatible version. I ll try to investigate Csv like parsing
(possible quoting) next week

**Comment by darkermatter** [comment]
The csv route looks like a minefield. What if somebody wants quoted titles, etc?

Don't forget, it's your project, set some rules and limitations. If people don't like it, then they can submit code like the other contributors! :-)

**Comment by e3rd** [comment]
This looks like to right way!

I've improved answers around: https://stackoverflow.com/questions/11456850/split-a-string-by-commas-but-ignore-commas-within-double-quotes-using-javascript

The solution seems to handle the right way both the arguments without quotes and with them, allowing to use other quotes and slashes within.

```js
var str = ', b, c, "d, e,\" " f", g, h';
str.split(/,(?![^"]*"(?:(?:[^"]*"){2})*[^"]*$)/).map(s => s.trim()).map(s => (s[0] == '"' && s.slice(-1)=='"')?s.slice(1,-1):s)
// ["", "b", "c", "d, e," " f", "g", "h"]
```

**Comment by e3rd** [comment]
Implemented – take a look and comment if you want.
