### ISSUE TITLE
Extension is incompatible with GNOME 40

### ISSUE THREAD

**Issue by dextersgenius** [CZ-NIC/run-or-raise#33]
I'm unable to install the extension via extensions.gnome.org.  The last compatible version appears to be 3.38.1. Can this extension please be updated to support the latest GNOME release?

**Comment by e3rd** [comment]
What's written in the `/var/log/syslog` please? As I do not have access to Gnome 40 yet, I'd appreciate some aid.

**Comment by e3rd** [comment]
ping

**Comment by dextersgenius** [comment]
Hi @e3rd , there's no logs because I'm unable to install it. extensions.gnome.org doesn't allow me to install, it says that it's incompatible. The last compatible version is 3.38.1. Is there a way to manually install and test this?

**Comment by e3rd** [comment]
If you have your extensions at `/home/$USER/.local/share/gnome-shell/extensions/`, put there folder `run-or-raise@edvard.cz` with the contents of the current master and in `metadata.json` change the version to `"shell-version": ["40"],`.

(Unfortunately, Ubuntu 21.04 seem to not include Gnome Shell 40 yet so I have no means to debug the extension porting  https://gjs.guide/extensions/upgrading/gnome-shell-40.html#contents )

**Comment by ofw** [comment]
> If you have your extensions at `/home/$USER/.local/share/gnome-shell/extensions/`, put there folder `run-or-raise@edvard.cz` with the contents of the current master and in `metadata.json` change the version to `"shell-version": ["40"],`.

It works fine if I add `"shell-version": ["40", "40.1"],`.

**Comment by e3rd** [comment]
Amazing news, I'll pack a new version then!

**Comment by e3rd** [comment]
New extension version was approved. In case of an error, I'd be glad if you reopen.
