### ISSUE TITLE
Minimize on Unfocus broken?

### ISSUE THREAD

**Issue by humanplayer2** [CZ-NIC/run-or-raise#36]
**First, praise:**

I am on Pop!_OS 21.04 on Wayland, making use of the tiling feature, and am absolutely overjoyed I have found this extension! I was looking for a "drop down filemanager" that I can use to overlay my tiled windows---thank you for providing that!

**Second, the issue:**

I would like my called window to minimize when it looses focus. This is sounds like what is implemented by @coddingtonbear in [#24](https://github.com/CZ-NIC/run-or-raise/pull/24). But I don't see the behavior I expected: 

    <Shift>F5:minimize-when-unfocused,nemo,nemo,

will make the shortcut run Nemo/focus it if not focused, and minimize it if I press it again, but if I shift the focus from the called window---e.g., by mouse-click or shortcut---the called window does not minimize.

Was the window supposed to minimize when thus loosing focus, or is the described the intended behavior?

**Comment by e3rd** [comment]
hi, thanks for posting, I'll try to get to you within a week

**Comment by humanplayer2** [comment]
Then I am seeing the intended behavior---which I also appreciate a lot! Thank you for the PR and the clarification, @coddingtonbear!
