### ISSUE TITLE
<Application> is ready notifications on Gnome Shell 41.0

### ISSUE THREAD

**Issue by DaanDeMeyer** [CZ-NIC/run-or-raise#37]
On Fedora 35 with Gnome shell 41 on Wayland, every time I switch between windows using a shortcut, a notification shows up saying the window I'm switching to is ready. This notification isn't useful so if possible it should be removed.

**Comment by e3rd** [comment]
I understand your issue however this has nothing in common with run-or-raise, see https://askubuntu.com/questions/1286206/how-to-skip-the-is-ready-notification-and-directly-open-apps-in-ubuntu-20-4 . My personally, I suppressed the notification as well, wondering why it exists.
