### ISSUE TITLE
Not compatible with Gnome 41.1

### ISSUE THREAD

**Issue by ofw** [CZ-NIC/run-or-raise#39]
Just updated Gnome to 41.1 and the extension stopped working and system said it's incompatible: 

![image](https://user-images.githubusercontent.com/4242339/141251652-17eb989e-8916-474b-9945-e79b3cc7ee17.png)

**Comment by e3rd** [comment]
What's your OS now? Would you be able to install the extension here from github? If so, I'd be interested in any logs produced to /var/log when trying to start it.
(If you have other extensions, the key would be just to place the files into ~/.local/share/gnome-shell/extensions/ and reload the shell.)

**Comment by ofw** [comment]
I installed it from github and it works. OS is Arch Linux. I Couldn't find any logs. I think we may close this for now as it works from github.

**Comment by e3rd** [comment]
Cool, you relieved me the worries! I'll try just to enlist the version or so...

**Comment by e3rd** [comment]
What about now? Have you stopped seeing "incompatible" at the https://extensions.gnome.org/extension/1336/run-or-raise/ when I've manually added 41 into enlisted versions please? (And I've also added a new flag `"disable-extension-version-validation": true` to prevent this in the future.)

**Comment by ofw** [comment]
Yes, it shows that everything is correct.
![image](https://user-images.githubusercontent.com/4242339/141427562-84d95bbe-3229-4dbf-ae32-75764b0242e9.png)

**Comment by e3rd** [comment]
Thanks!
