### ISSUE TITLE
Feature Request: dbus interface

### ISSUE THREAD

**Issue by chmouel** [CZ-NIC/run-or-raise#40]
Maybe this is out of scope of this project but it would be great if there was a dbus interface to the extension call.

The idea would be to be able to call the run-or-raise extension from a script or other calls, to get to it. Since on wayland we can't do this anymore with other tools.

some example here:

https://github.com/ickyicky/window-calls/blob/main/extension.js

**Comment by e3rd** [comment]
not wanted anymore #41
