### ISSUE TITLE
"Cannot get system pointer"

### ISSUE THREAD

**Issue by kuba-orlik** [CZ-NIC/run-or-raise#45]
Every time I switch windows using run-or-raise, the switch works, but I get a notification saying:

```
Cannot get system pointer, please report with `gnome-shell --version`
```

Here's the output of `gnome-shell --version`:

```
GNOME Shell 42.0
```

**Comment by e3rd** [comment]
Hi, thanks for reporting this! Do you use mouse centering either globally in the extension options
![image](https://user-images.githubusercontent.com/6942231/163380056-055669f1-9f90-4246-95c8-e51781461c1b.png)
or as a shortcut [keyword](https://github.com/CZ-NIC/run-or-raise#center-mouse-to-focused-window)? If not, turn this off to get rid of the message right know.

Or you'll have to wait till I find out how the API changed, sorry that the message bothers you .

**Comment by kuba-orlik** [comment]
Yes, I did have that option switched on. Disabling it fixed the issue. I'm fine with this config being off. Thanks! <3

**Comment by e3rd** [comment]
Thanks to you, we've spotted down the issue. It will work in the next version. Have a nice day.
