### ISSUE TITLE
Feature request: Move to workspace of open window

### ISSUE THREAD

**Issue by humanplayer2** [CZ-NIC/run-or-raise#46]
So, the opposite of `move-window-to-active-workspace`: I would like to be able to set a shortcut so I move to the workspace of an open window.

If it exists, then I apologize: Using no mode or `switch-back-when-focused`, the window is pulled to my current workspace.

**Comment by e3rd** [comment]
Hi, (before I start investigating) do you have all your global settings off please? Because moving to the workspace of an open window if my default.

![image](https://user-images.githubusercontent.com/6942231/193520995-bc23713d-a625-448c-867c-7b65c1d86c20.png)

**Comment by humanplayer2** [comment]
Sorry! I've been so used to setting the shortcuts in the settings file along with my other dotfiles (thank you for implementing it like that, it's so easy to edit) that I not even considered that there were other options!
