### ISSUE TITLE
extension not compatible with Gnome 43

### ISSUE THREAD

**Issue by jdeut** [CZ-NIC/run-or-raise#48]
![image](https://user-images.githubusercontent.com/1739296/194145565-ee3d5414-befc-41bd-9c4b-1019b7855db1.png)

best regards

**Comment by e3rd** [comment]
At the first glance at https://gjs.guide/extensions/upgrading/gnome-shell-43.html I did not see any change. What OS do you have? Don't you have something in the logs?

**Comment by e3rd** [comment]
Check current Gnome extensions version, I've made it available for 43 and let me know please :)

**Comment by jdeut** [comment]
Thank you for your quick response.

In the meantime `gnome-extensions-app` had offered me to update `run-or-raise`. After restarting `gnome-shell` everything works as expected again. As i run `debian testing` i guess the error was caused by multiple non-synchronized transitions of gnome related software from 42 to 43 during the last couple of days.

Best regards and everytime there's a problem with `run-or-raise` i just realize how essential your extension is for my workflow!

**Comment by e3rd** [comment]
Thanks, cool! :) In fact it was caused by mere missing "43" in metadata.json, it seems it is advisable to state each version separately.
