### ISSUE TITLE
minimize-when-unfocused does not minimize when unfocusing

### ISSUE THREAD

**Issue by humanplayer2** [CZ-NIC/run-or-raise#49]
When cycling through more than one window using

    <Super>2:minimize-when-unfocused,kitty,

the instances that lose focus are nor minimized. It seems that once more than one window is in the cycle, the minimization is disabled.

Is this intended?

**Comment by e3rd** [comment]
I think this is intended if I understand the explanation in #36 we've had last year. If you have different work flow, open a PR or design new keywords or summon original author of the `minimize-when-unfocused` keyword... :)

```js
if (seen) {
            if (!seen.has_focus()) {
                this.focus_window(seen);
            } else {
                if (mode.get(Mode.MINIMIZE_WHEN_UNFOCUSED)) {
                    seen.minimize();
                }
...
```

**Comment by humanplayer2** [comment]
Oh, that's so embarrassing.. Well, it goes to show it's not something that bothers me in my workflow. I came noticed it again as I write a comment about using Run or Raise to define a scratchpad on Forge. To that end, it might be fun trying my hand a t defining a new mode :D
