### ISSUE TITLE
No shortcuts file created

### ISSUE THREAD

**Issue by monkeydri** [CZ-NIC/run-or-raise#5]
I just installed this extension and noticed a small bug when trying to open went to open shortcuts.conf file, either by run-or-raise settings (Gnome Tweaks > run-or-raise > cog icon > click "open shortcuts.conf file" : nothing happens) or by opening the file directly : ~/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz/shortcuts.conf

Here is the error message :

![screenshot from 2018-01-12 17-21-04](https://user-images.githubusercontent.com/18724661/34884640-9a5ebce2-f7bd-11e7-86f3-2e900d0da599.png)

run-or-raise v2
gnome-shell 3.26.2
ubuntu 17.10

Of course the fix is obvious (delete it and copy it again from shortcuts.default) but I just wanted to let you know

**Comment by e3rd** [comment]
I'm glad that you know the fix so it hasn't got enourmous priority. I'll try to investigate, thanks!

**Comment by monkeydri** [comment]
I think the problem is that you left a `shortcut.conf` symlink in the release (on gnome shell extensions site) whereas there should be none because on start, when no `shortcut.conf` is found, `shortcuts.default` is copied in `extension.js` :

```
enable() {        
    try {
        var s = Shell.get_file_contents_utf8_sync(confpath);
    }
    catch(e) {
        log("Run or raise: can't load confpath" + confpath + ", creating new file from default");                
        imports.misc.util.spawnCommandLine("cp " + defaultconfpath + " " + confpath);
        try {
            var s = Shell.get_file_contents_utf8_sync(defaultconfpath); // it seems confpath file is not ready yet, reading defaultconfpath
        }
        catch(e) {
            log("Run or raise: Failed to create default file")
            return;
        }        
    }
```

**Comment by e3rd** [comment]
(fixed a long time ago :) )
