### ISSUE TITLE
Shortcut to Nautilus does not cycle through windows

### ISSUE THREAD

**Issue by yttrium** [CZ-NIC/run-or-raise#50]
Ubuntu 22.04, Wayland

With nautilus (and perhaps other applications, there is erroneous behavior when multiple windows are open:

<Super>f,nautilus,nautilus,  # same for: nautilus,org.gnome.Nautilus,

does not cycle through the open windows. What is worse, the same window is always focussed, even if previously, another nautilus window was selected.

Steps to reproduce:
Empty desktop

1) Define shortcut key as above
2) Hit the shortcut to open a nautilus window. Hit Ctrl+N to open a second nautilus window
3) Open a browser
4) Press shortcut key: the second nautilus window is focused (correctly, thus far)
5) Press shortcut key again: nothing changes (expected: the other nautilus window is now focused)
6) Press Alt+key-above-tab to bring first nautilus window in focus
7) Switch to browser
8) Press shortcut key: the second nautilus window is focused (expected:  the first window should be focused)

This erroneous behavior is specific to nautilus - it works correctly with e.g. multiple windows of gedit or firefox.

**Comment by e3rd** [comment]
Thanks for having written the steps for reproduce! Are you sure you've used the same `wm_class` string as seen in the `lg`? For me, the following (mind the big letter 'o') works perfectly.

```
<Super>m,nautilus,Org.gnome.Nautilus,
```

**Comment by yttrium** [comment]
Thank you for getting back so quickly. I tested on a fresh account and
there, any syntax works perfectly. On my current account, the most simple
form, "<Super>m,nautilus,,", does work as expected. The only drawback is
that current window, with "Nautilus" in its title, is also cycled to.

The issue thus can be closed. I still will experiment a little to see if it
is interference with another extension, though.

**Comment by e3rd** [comment]
I wonder that "any syntax" would work perfectly, I thought `wm_class` is case sensitive. Either `Org.gnome.Nautilus` or `org.gnome.Nautilus` should work, not both.

(Shortcut `<Super>m,nautilus,,` launches command nautilus every time and the program is so clever that it checks whether it is already running and if so, gots raised. It might be slightly slower to cycle some programs that way.)

If you need anything, I'm here :)
