### ISSUE TITLE
Use <Return> key

### ISSUE THREAD

**Issue by Paul-Aime** [CZ-NIC/run-or-raise#52]
I would like to use the following mapping: 

```
<Super><Shift><Return>,kitty,,
```

Is it possible?
The `<Return>` key seems not to be understood.

**Comment by e3rd** [comment]
Return is not a modifier, but a mere key. ;)

```
<Super><Shift>Return,kitty,,
```

**Comment by Paul-Aime** [comment]
Thanks for the answer. However it seems like it work for me, I got the following when enabling the extension: `Unable to grab accelerator: <Super><Shift>Return,kitty,,`.

**Comment by e3rd** [comment]
Strange! Ehat's your OS and Gnome version? I ll try to look at it in the
following week.
Is there any other app that might interfere with the shortcut? Like
super+alt+shift+enter would eork?

**Comment by Paul-Aime** [comment]
My bad you're right it was shadowed by the GNOME shortcut I used to have for X.
Thanks a lot!
