### ISSUE TITLE
GNOME 44 compatibility : Gdk.Keymap is undefined

### ISSUE THREAD

**Issue by xalt7x** [CZ-NIC/run-or-raise#54]
Version for GNOME 43 used to work for GNOME 44 beta.
I just needed to edit
`~/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz/metadata.json`
But after update to GNOME 44 RC1 extension doesn't load because of error
`Gdk.Keymap is undefined`

**Comment by e3rd** [comment]
I am out of office, will tackle this no earlier than at the end of Mar :(

**Comment by e3rd** [comment]
Could you please try it with the current Gnome 44? I've checked https://gjs.guide/extensions/upgrading/gnome-shell-44.html and there is no mention about `Gdk`. Maybe it was just an error in RC1...

**Comment by xalt7x** [comment]
Now it works.
Thanks.

**Comment by xalt7x** [comment]
I'm re-opening this issue since that's still the case with X11 session (Wayland in fine).

**Comment by e3rd** [comment]
Thanks for the report, you do not need to try it now, I bet that's on me

**Comment by nose-gnome** [comment]
I also have this issue.  It started happening when I updated to Ubuntu 23.04 with Gnome 44.0.  I am using X11, I haven't tested it with Wayland yet

**Comment by flyboy14** [comment]
Same here.
Arch Linux, Gnome 44.1 
Worked well on 43.5, throws `Gdk.Keymap is undefined` after upgrade.

**Comment by e3rd** [comment]
Thanks to you all for the investigation! Does current master work for any of you please?

**Comment by karmicdude** [comment]
It works for me - Arch Linux, Gnome 44.1

**Comment by nose-gnome** [comment]
I will check in about an hour or so

**Comment by e3rd** [comment]
We've just released the new version. I beg the X11 users to check whether the new release (which the system should impose you automatically) works as expected. In doubt, we re-open the issue.
