### ISSUE TITLE
Combining modifiers does not register

### ISSUE THREAD

**Issue by grasegger** [CZ-NIC/run-or-raise#58]
Hi there, 

just stumbled upon this and it is exactly what I was searching for. However I ran into a problem while trying to configure the extension to meet my needs. I tried to add the followindg:
```
<Super><Shift>n,google-chrome,Google-chrome,
```
However all I get when pressing that combo is `N`.

I am on Gnome 44, system is Fedora Silverblue, Wayland Session, using a bluetooth keyboad.

Did I misunderstand the docs regarding the config or is this a (wayland related) bug?

**Comment by e3rd** [comment]
Hi, what do you mean by "all I get is `N`", like big letter N is output on the screen? Does any other shortcut work at the same moment?

**Comment by e3rd** [comment]
So if you use this

```
<Super><Ctrl><Alt>b,notify-send Hello world5
<Super><Alt>b,notify-send Hello world4
<Super><Ctrl>b,notify-send Hello world3
<Super><Shift>b,notify-send Hello world2
<Super>b,notify-send Hello world1
<Super>c,notify-send Hello world0
```

only `Hello world1` and `Hello world0` works then?

Is there any difference using the bluetooth and the integrated keyboard?

Is there anything interesting in the /var/log/syslog in the moment you restart the extension (in order new shortcuts to work)?

**Comment by e3rd** [comment]
:D cool, have a nice day!
