### ISSUE TITLE
Support for Gnome 45

### ISSUE THREAD

**Issue by romixch** [CZ-NIC/run-or-raise#60]
It would be great to see this extension work in Gnome 45.

**Comment by e3rd** [comment]
Since I have no Gnome 45 installed yet, I tried a blind version only. Will you help me, trying it? Could you find some mention in syslog to see whether there is an error I could easily spot?

**Comment by e3rd** [comment]
Anyone had the chance to try the Gnome 45 branch to see whether that works?

**Comment by romixch** [comment]
It wont work automatically. But there are good porting guides: https://youtu.be/OBnMl8Jk_Rg?si=CV4HEmWqyb7kwnWw
https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

**Comment by romixch** [comment]
Looking at the code it is probably not that hard. I may give it a try in some days.

**Comment by e3rd** [comment]
I've already implemented it two weeks ago, see the commit to the branch gnome45 ;) Are you able to download it and try it on your system?

**Comment by romixch** [comment]
OK. I have tested it. It does not run yet but I can send you a pull request when it does.

**Comment by e3rd** [comment]
Does it write something to the syslog? :)  
This morning, @teur fixed the import and pushed it into the gnome45 branch https://github.com/CZ-NIC/run-or-raise/tree/gnome45 , check rather that version now, thanks!

**Comment by romixch** [comment]
You are all too fast for me :-) I just fixed everything on my fork. I also reworked the preferences dialog to use libadwaita. It was too wide and I could not read all the text.

![grafik](https://github.com/CZ-NIC/run-or-raise/assets/1838576/e7f237c7-bff1-4ca0-891d-c591e140d39f)

**Comment by romixch** [comment]
By the way: I used Gnome OS Nightly to test the extension in Gnome 45. The easiest way is probably through Gnome Boxes: https://os.gnome.org/

**Comment by romixch** [comment]
To answer your question: Does it write something to the syslog?
After the patch of teur the extension functions properly as far as I can see. But the preferences dialog does not open. There is nothing in the syslog but I get an exception shown instead of the prefs dialog:

The settings of extension run-or-raise@edvard.cz had an error:
```
Error: Version 2.0 of GI module GIRepository already loaded, cannot load version 4.0
```

Stack trace:
```
require@resource:///org/gnome/gjs/modules/esm/gi.js:19:23
@gi://GIRepository?version=4.0:3:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

My patch also includes a fix for that.

**Comment by romixch** [comment]
Oh I'm glad that worked out! I could test it again with the current committed code. Or did you already test it on gnome 45?

**Comment by e3rd** [comment]
Oh yes please, test it, I didnt do that

**Comment by romixch** [comment]
I tested it again. I did not get any obvious errors. So I think it is ok.
Looking forward to get Gnome 45 from Manjaro now!

**Comment by kevinbburns** [comment]
When do you think this will be pushed out to the gnome.extensions site?

**Comment by e3rd** [comment]
(Just few more days, sorry)

**Comment by e3rd** [comment]
Finally submitted and under review by the gnome team

**Comment by e3rd** [comment]
(Released ✓)
