### ISSUE TITLE
request: raise-or-register with index

### ISSUE THREAD

**Issue by tennox** [CZ-NIC/run-or-raise#61]
I started from
```
<Super><Shift>1:raise-or-register
<Super><Shift>2:raise-or-register
```
but realized sometimes i want to change which window I want to register, but without closing the previously registerex one.
So I found out about this:
```
<Super><Shift>1:raise(1)
<Super><Shift>2:raise(2)
<Ctrl><Super><Shift>1:register(1)
<Ctrl><Super><Shift>2:register(2)
```

but I'd actually love have:

**`raise-or-register(1)`**

so that I can use the same keybinding for the first registration, but in case I need to change, can use the CTRL+ modifier to overwrite.

**Comment by e3rd** [comment]
Will you try the current master?
