### ISSUE TITLE
Feature request: Ability to run commands as root/with sudo

### ISSUE THREAD

**Issue by distbit0** [CZ-NIC/run-or-raise#66]
Hi. Due to the ease with which all shortcuts can be exported/imported from this extension, I have decided to use it for all my custom keyboard shortcut needs rather than the fedora custom keyboard shortcut config application.

I have, however, ran into an issue when trying to bind a shortcut to a command which requires root privileges. Is it currently possible to execute commands which require root privileges using this extension? many thx!

**Comment by e3rd** [comment]
Great to hear that! The exportability was a big issue for me too.

A simple `pkexec` won't work? On Ubuntu, it raises a password dialog when run I.E.

```
$ ls /root/.bashrc # denied
$ pkexec ls /root/.bashrc # dialog → allowed
```

For a repetive command I recommend `sudoers`.

**Comment by distbit0** [comment]
great thx that works.
