### ISSUE TITLE
"unable to grab accelerator" for slash and backslash

### ISSUE THREAD

**Issue by andreimatei** [CZ-NIC/run-or-raise#67]
Setting commands for slash and backslash doesn't seem to work (`<Super><Alt>/` and `<Super><Alt>\`). When restarting the extension, I get a notification saying "unable to grab accelerator <Super><Alt>/). Is this expected?

Is there a list of characters that are supported?

Thanks for this extension!

**Comment by e3rd** [comment]
I lo try to debug it the next week

**Comment by e3rd** [comment]
Just try `slash` keysym like `<Super><Alt>slash`, that works ;)

https://github.com/CZ-NIC/run-or-raise#shortcut

**Comment by andreimatei** [comment]
Thanks, that works!

FWIW, the docs on the topic where not clear to me. There is a "If you need to discover a keysym" paragraph, but the word "keysym" does not appear before, so it was not clear to me that the shortcuts use these keysyms.

**Comment by e3rd** [comment]
Thx, I should reword the paragraph then!
