### ISSUE TITLE
Mention out-of-the-box alternative (ab)using GNOME Shell "switch-to-application-N" dconf entries

### ISSUE THREAD

**Issue by ronjouch** [CZ-NIC/run-or-raise#68]
Hi there.

I've been enjoying your extension for a couple months. But while installing a new machine, came the inevitable (for me) quest to minimize extension usage, for reasons you can imagine: I have nothing against extension authors, but I do have a gripe against GNOME Shell major upgrades breaking extensions (as extensions monkeypatch and have no stable API).

Turns out, I was able to find a way! To get a basic "native" (a.k.a. no extension) run-or-raise under Shell,

1. Pin your favorite apps to Activities
2. Set dconf values `org.gnome.shell.keybindings` / `switch-to-application-N` to your desired keyboard shortcut (where `N` is `1..9`), replacing / adding to default `<Super+N>`
3. Never re-order your pinned apps

That's it; enjoy a basic run-or-raise in Shell with no extension! Mentioning it here, in case it interests passerbys, or in case it's helpful next time the extension is broken after a Shell major upgrade. Maybe it's something you could mention in an `## Alternatives` section of the README.

## Caveats

- Limited to 9 apps! Choose wisely! 😄
- No wmclass-regex support, limited to your `.desktop` entries `WMClass`
- No run-or-raise fancy "Modes"

**Comment by ronjouch** [comment]
Oooooooooh I just saw that README already hints at this:

> _But what if you use more programs than nine_

... but it wasn't clear to me the first time I read it, and I didn't know until today that the `Super+N` kb shortcut for these 9 apps could be changed.

→ Still IMHO feels an `## Alternative` README section would help surface it. Or not, your call 🙂. Thanks for all the fish!

**Comment by e3rd** [comment]
Ok, thanks, just suggest in a PR :)

**Comment by ronjouch** [comment]
> Ok, thanks, just suggest in a PR :)

Done in https://github.com/CZ-NIC/run-or-raise/pull/69
