### ISSUE TITLE
Logout is still needed under Wayland

### ISSUE THREAD

**Issue by thebunnyrules** [CZ-NIC/run-or-raise#7]
Great extension! 

It says in Run or Raise prefs that logout is no longer needed after shortcut.conf is edited. I just wanted to bring it to your attention that this does not seem to be the case in Wayland (at least as far as I can tell from my own experience). I still need to logout to have the extension see my changes.

Having to logout makes no difference for me but I thought I'd let you know since it may cause some confusion with your users.

**Comment by e3rd** [comment]
Thanks :)
Editing only is not sufficient, you are told in prefs to reload the extension (and in readme.md "Just disable & enable the extension"). Did you try to disabled & enable the extension please?

![image](https://user-images.githubusercontent.com/6942231/37065563-8e542ff0-21a1-11e8-9256-96e6fc20f856.png)

**Comment by thebunnyrules** [comment]
Hehehehe... No I didn't.... It works now. Sorry about that. I had tried that trick on a couple of other extensions and it didn't work so I had written it off. Woops. Thanks for you help and patience... :+1:
