### ISSUE TITLE
Error: TypeError: window_title[titleFn] is not a function

### ISSUE THREAD

**Issue by distbit0** [CZ-NIC/run-or-raise#72]
After installing what I think is an update to this extension, I am experiencing the following issues:

- switching to an application now incurs a 1 second delay, if successful
- however with some applications that are not successful, I incur this error when attempting to switch to them:
TypeError: window_title[titleFn] is not a function
![image](https://github.com/CZ-NIC/run-or-raise/assets/10890247/53c4d3d2-87ca-4f9b-afc3-8e224a7f0996)

So far Brave is the only application which causes this error when attempting to switch to it. Interestingly though, Brave opens successfully the first time the shortcut is used (i.e. if it is not already running), however fails to be refocused upon future attempts to use the associated shortcut, due to the above mentioned error.

Un-focusing also does not seem to be working for any application, even those which raise or run is able to focus after a multi-second delay. However I do not encounter any error message when attempting, unsuccessfully, to un-focus a window which is currently focused. This used to work perfectly until what seems to be a recent update. 

Un-focusing does however trigger the `TypeError: window_title[titleFn] is not a function` error message when attempting to un-focus an application for which focusing also fails, such as brave.
I have also noticed that re-focusing some applications causes them to be opened from scratch, despite the fact that they previously used to re-focus successfully without being re-executed. Specifically, this occurs for Obsidian.

These are config options:
![image](https://github.com/CZ-NIC/run-or-raise/assets/10890247/b6404e95-9efb-4db0-b067-5ce7acb22a12)

And my settings file:

```
# Here you list all the shortcuts.
#
# The shortcuts may be defined in two ways:
#
# 1. Run-or-raise form: shortcut,command,[wm_class],[title]
#        * `wm_class` and `title` are optional and case sensitive
#        * if none is set, lowercased launch `command` is compared with lowercased windows wm_classes and titles
#
# 2. Run only form: shortcut,command
#
#
# In fact, full form is `shortcut[ char][:mode],command,[wm_class],[title]`
# while `char` allows you to use layered shortcuts and `mode` to further specify circumstances.
#
# =================
# Run or raise form
# =================
#
#
# This line cycles any firefox window (matched by "firefox" in the window title) OR if not found, launches new firefox instance.
#<Super>f,firefox,,
# This line cycles any open gnome-terminal (matched by wm_class = Gnome-terminal on Ubuntu 17.10) OR if not found, launches new one.
# If you're using Arch, you may want to match by wm_class = gnome-terminal-server , just check yourself by Alt+F2/lg/Windows
#<Super>r,gnome-terminal,Gnome-terminal,


# You may use regular expression in title or wm_class.
# Just put the regular expression between slashes.
# E.g. to jump to pidgin conversation window you may use this line
# (that means any windows of wm_class Pidgin, not containing the title Buddy List)"
#<Super>KP_1,pidgin,Pidgin,/^((?!Buddy List).)*$/


# Run only form
# =============
#
# This line will launch the `notify-send` command.
#<Super>y,notify-send Hello world

# This layered shortcut will output the text only when you write `hello` after hitting <Super>e.
#<Super>e h e l l o,notify-send Layered hello

# This layered shortcut will not interfere with the shorcut above that is launching a terminal.
#<Super>e <Super>r,notify-send Layered 'Terminal was not launched.'

# Blank lines are allowed. Line starting with "#" means a comment.
# Now delete these shortcuts and put here yours.
# How to know wm_class? Using xprop or the looking glass tool, see README.md



# Converted Shortcuts

# Opens Nautilus file manager
<Super>n,nautilus,org.gnome.Nautilus,

# Opens Gnome System Monitor
<Super>m,gnome-system-monitor,gnome-system-monitor,

# Opens Gnome Control Center (Settings)
<Super>p,gnome-control-center,org.gnome.Settings,

# Opens KeePassXC password manager
<Super>k,keepassxc,org.keepassxc.KeePassXC,

# Opens Signal desktop application
<Super>s,flatpak run org.signal.Signal,Signal,

# Opens Discord in Brave browser
<Super>d,brave-browser --profile-directory=Default --app=https://discord.com/channels/865432401270145054/1083781888163979275,,Discord

# Opens Brave browser
<Super>w,brave-browser,Brave-browser,Brave

# Opens Telegram desktop application
<Super>t,/opt/Telegram/Telegram,org.telegram.desktop._3e485da34fc040f9218e3891ecde1e6c,

# Opens Obsidian note-taking app
<Super>z,flatpak run md.obsidian.Obsidian,obsidian,

# Opens Visual Studio Code
<Super>v,code,Code,

# Opens ProtonMail in Brave browser
<Super>e,brave-browser --profile-directory=Default --app=https://mail.proton.me/u/1/inbox,,Proton Mail

# Opens Gnome Terminal
<Super>x,gnome-terminal,gnome-terminal-server,

# Opens Gnome Text Editor
<Super>g,gnome-terminal -- bash -c 'nvim; exec bash',,Terminal

# Opens Gnome Calculator
<Super>c,gnome-calculator,org.gnome.Calculator,

# Pause/play audio
<Ctrl><Super>p,playerctl play-pause

# toggle audio output
<Ctrl><Super>a,python3 /home/pimania/dev/manageAudio/switchAudioSink.py

# update blog
<Ctrl><Super>b,/home/pimania/dev/autoBlogPost/run.sh

#vim hints
<Ctrl><Super>v,brave-browser https://vimsheet.com/
```

Many thx!

**Comment by e3rd** [comment]
Sorry, I ll repair asap.

**Comment by distbit0** [comment]
Thank you very much! @e3rd

**Comment by e3rd** [comment]
I've definitely spotted an error that might cause that (yesterday evening but I had no time to fix). I am not quite sure whether this solves all the problems – because application launching method changed due to a weird output into syslog. I'd be glad if you could recheck when the new version 34 is released by the Gnome team (currently under review, should be in few hours). Or if you are in the rush and able to, try with the current master. (Which is difficult as you need to replace your source files and log out.)

**Comment by e3rd** [comment]
The new version has been released, check it when you have time :)

**Comment by distbit0** [comment]
Just updated the extension and that seems to have resolved ALL issues :+1: thanks so much for addressing this so quickly.
