### ISSUE TITLE
Run a command just after running or raising a program ?

### ISSUE THREAD

**Issue by ManUtopiK** [CZ-NIC/run-or-raise#73]
Hi!

Thanks a lot for this extension. I use it since few days and it works like a charm.

I try to build more complex shortcuts and I wonder if it's possible to run a command just after running or raising a program ?

Let's say I want to launch or raise the terminal, and send up arrow + enter with xdotool.
Do you know if it's possible, or any workaround to do that ?
Thx

**Comment by e3rd** [comment]
Thanks! Have you tried https://github.com/CZ-NIC/run-or-raise?tab=readme-ov-file#always-run ?

**Comment by ManUtopiK** [comment]
Awesome! I missed this part. Thank you so much!
