### ISSUE TITLE
Ubuntu 22.04 also uses "gnome-terminal-server" as wm_class for Gnome Terminal

### ISSUE THREAD

**Issue by jvalrog** [CZ-NIC/run-or-raise#74]
Just so you know, the configuration file says to use "gnome-terminal-server" if you use Arch, but it's also the same in Ubuntu 22.04 (the only one I've tried).

![image](https://github.com/CZ-NIC/run-or-raise/assets/456311/e141f31b-a21d-4bc8-b60b-2532c62f1919)

Also, many many thanks for this amazing extension, I've been searching for a scratchpad extension for ages and this one works flawlesly!

**Comment by e3rd** [comment]
Neat, I'll mention it in the readme
