### ISSUE TITLE
GNOME 46 support

### ISSUE THREAD

**Issue by bubner** [CZ-NIC/run-or-raise#76]
Hello, GNOME 46 was released and I recently upgraded to it. If you could update the extension to support GNOME 46 that would be great :)

**Comment by e3rd** [comment]
Please try now, you'll be the first one :)

**Comment by bubner** [comment]
All is working, thanks!

**Comment by StephanDollberg** [comment]
I don't think the change to add "46" to metadata.json was committed?

**Comment by e3rd** [comment]
Strange! I see it live, you don't?

![image](https://github.com/CZ-NIC/run-or-raise/assets/6942231/21ff25ec-0d8a-4345-84c3-08c2f615a1d1)

**Comment by StephanDollberg** [comment]
Oh sorry, I was using a source checkout from the repo which doesn't have it: https://github.com/CZ-NIC/run-or-raise/blob/main/metadata.json#L7

I assume the metadata somehow gets autogenerated when downloading from the gnome extensions site?

**Comment by e3rd** [comment]
Sorry I didn't pushed to the repo before!

(No, the metadata is a little pain, I have to put it there manually before uploading to gnome for every new version. It's a minor step that lags the users. I cannot put a non-existent gnome version to be future-version-proof and I cannot turn off version checking as it would cause old gnome versions to download a new incompatible gnome version.)
