### ISSUE TITLE
Extension stop working after logout

### ISSUE THREAD

**Issue by victorpigmeo** [CZ-NIC/run-or-raise#77]
After I logout the extension stops working and I need to disable and enable it. Also, I put 'emacs' to a shortcut but it opens the "wrong" emacs, I want to use the "client" one, but I don't know how to specify that.

**Comment by victorpigmeo** [comment]
It is my first time using the extension 😅 I was using BSPWM and now I'm using Gnome vanilla on a Debian 12 (And I got this open or raise thing on BSPWM). 
There is nothing on `/var/log/syslog`.
The thing is that when I shutdown the PC or logout my shortcuts (like `<Super>1` or `<Super>4`) comes back to the original gnome behavior (Open the files app, or libreoffice). Then if I open the extensions and disable -> enable it works again.
Normally I open emacs on the gnome launcher, in my case I have 2 options: 
Emacs (client) -> Opens a client to the daemon emacs that is running
Emacs -> Opens emacs without using the daemon
When I open emacs (on the launcher) the extension works great, it raises it when I use the shortcut. But when emacs is not opened and I use the shortcut it opens the Emacs (without daemon) option.
As I said, I'm using a Debian 12 with vanilla gnome, and it is almost a fresh install

**Comment by e3rd** [comment]
Other shortcuts like `<Super>e` works well? Is the case for the shortcuts concurrently used for app launching?

Are you able to find the Emacs (client)  fille at  `.local/share/applications` ?

**Comment by victorpigmeo** [comment]
I didn't test it yet, but as soon I test I post here the outcome

**Comment by e3rd** [comment]
Yeah but other shortcuts like <Super>e works well?

Are you able to find the Emacs (client) fille at .local/share/applications ?

**Comment by e3rd** [comment]
no reaction, no info, problem might have vanished
