### ISSUE TITLE
Add support for older versions of gnome-shell

### ISSUE THREAD

**Issue by tylla** [CZ-NIC/run-or-raise#9]
It would be awesome if run-or-raise would run on older versions of gnome-shell. I am using Debian 9 which has an older version of Gnome-Shell, 3.22.2.
At least I suspect that this is why (after trying to hack this extension to my system by modifying the shell-version in the metadata.json) I get an exception:
`Exception in callback for signal: extension-found: SyntaxError: class is a reserved identifier @ /home/tylla/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz/extension.js:61
`
Btw: thanks for the idea, nice extension, I'm really looking forward to be able to try it.

**Comment by e3rd** [comment]
Would you try current version please? If that works, good for us, if it doesn't I fear I have no more clues to debug it remotely to Debian 9. Please let me know about the result!

**Comment by tylla** [comment]
I tried the new version and it works perfectly.
Now finally I can use those nice shortcuts as they should work.
Thank you very much for the prompt fix!
